[package]
name = "watklok-native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.2", features = ["napi10", "tokio_rt", "async"] }
napi-derive = "3.6.3"
once_cell = "1.21.4"
rand = "0.10.2"
dashmap = "7.0.0-rc2"
arc-swap = "1.9.2"

# For OGGParser
bytes = "1.12.1"
memchr = "2.8.3"

# For crypto
davey = "0.1.4"
aead = "0.6.1"
aes-gcm = { version = "0.11.1", features = ["aes"] }

# Профиль релиза
[profile.release]
opt-level = 3            # Максимальная оптимизация скорости кода (по умолчанию в release)
lto = true               # Включает Link-Time Optimization (оптимизация между всеми крейтами)
codegen-units = 1        # LLVM оптимизирует всё как один блок, улучшая инлайнинг и глобальный анализ
panic = "abort"          # Отключает раскрутку стека при панике (уменьшает размер файла и ускоряет код)
strip = true             # Полностью удаляет отладочные символы и таблицы из бинарника