name: Build Rust modules + Typescript
on:
  push:
    branches: [ "main", "beta" ]
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 25.x ]
        settings:
          # Linux
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npx napi build --release --platform --cargo-cwd ./src-rs

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: npx napi build --release --platform --zig --cargo-cwd ./src-rs

          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: npx napi build --release --platform --zig --cargo-cwd ./src-rs

          # Windows
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: npx napi build --release --platform --cargo-cwd ./src-rs

          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: npx napi build --release --platform --cargo-cwd ./src-rs

          # macOS
          - host: macos-latest
            target: x86_64-apple-darwin
            build: npx napi build --release --platform --cargo-cwd ./src-rs

          - host: macos-latest
            target: aarch64-apple-darwin
            build: npx napi build --release --platform --cargo-cwd ./src-rs

          # Android
          - host: ubuntu-latest
            target: aarch64-linux-android
            build: npx napi build --release --platform --zig --cargo-cwd ./src-rs

          - host: ubuntu-latest
            target: armv7-linux-androideabi
            build: npx napi build --release --platform --zig --cargo-cwd ./src-rs

    name: build-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4

      # Node Setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present

      # Rust Setup
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Setup Zig
        if: contains(matrix.settings.build, '--zig')
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: ${{ matrix.settings.build }}

      # Prepare builds
      - name: Build final artifact
        run: |
          mkdir -p build/native
          cp index.js build/native/ || true
          cp *.ts build/native/ || true
          cp *.node build/native/ || true
          rm -rd node_modules

      # Create builds
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            **/*
          if-no-files-found: error